language: node_js
node_js: "11"
os:
  - linux
#  - osx
dist: trusty
osx_image: xcode8.3
sudo: false

# cache:
#   directories:
#     - node_modules
#     - $HOME/.cache/electron

addons:
  apt:
    packages:
      - fakeroot
      - rpm

branches:
  only:
    - master
    - develop
    - /^v\d+\.\d+\.\d+/

install:
  - npm install
  - npm update

script:
  - npm run publish
